<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-M4N4JHAP" ignored="0" name="Addition" tests="10" failures="9" timestamp="2021-03-15T10:01:30 GMT" time="70.971" errors="0">
  <testcase name="AddAscendRangeAndDescendRange" time="7.778" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [80235.0] but found [191235.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [80235.0] but found [191235.0000000001]
at Acacemy.additionTest.AddAscendRangeAndDescendRange(additionTest.java:29)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddAscendRangeAndDescendRange -->
  <testcase name="AddBigNumberandOne" time="6.611" classname="Acacemy.additionTest"/>
  <testcase name="AddDecimalNumbers" time="5.967" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [5.34] but found [35.343000000100005]">
      <![CDATA[java.lang.AssertionError: expected [5.34] but found [35.343000000100005]
at Acacemy.additionTest.AddDecimalNumbers(additionTest.java:104)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddDecimalNumbers -->
  <testcase name="AddMorethanTwoNumbers" time="5.416" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [21.0] but found [51.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [21.0] but found [51.0000000001]
at Acacemy.additionTest.AddMorethanTwoNumbers(additionTest.java:83)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddMorethanTwoNumbers -->
  <testcase name="AddNegativeandPositiveNumbers" time="5.274" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [-7.0] but found [11.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [-7.0] but found [11.0000000001]
at Acacemy.additionTest.AddNegativeandPositiveNumbers(additionTest.java:97)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddNegativeandPositiveNumbers -->
  <testcase name="AddNmmbersgivesSevenDigitResult" time="5.815" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [5555555.0] but found [3.5565565565E10]">
      <![CDATA[java.lang.AssertionError: expected [5555555.0] but found [3.5565565565E10]
at Acacemy.additionTest.AddNmmbersgivesSevenDigitResult(additionTest.java:39)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddNmmbersgivesSevenDigitResult -->
  <testcase name="AddTwoBigNumbers" time="6.243" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [9.34934934E8] but found [1.65630845967E11]">
      <![CDATA[java.lang.AssertionError: expected [9.34934934E8] but found [1.65630845967E11]
at Acacemy.additionTest.AddTwoBigNumbers(additionTest.java:52)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddTwoBigNumbers -->
  <testcase name="AddTwoSingleDigits" time="5.287" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [8.0] but found [8.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [8.0] but found [8.0000000001]
at Acacemy.additionTest.AddTwoSingleDigits(additionTest.java:90)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddTwoSingleDigits -->
  <testcase name="AddZeroAndOne" time="5.222" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [1.0] but found [1.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [1.0] but found [1.0000000001]
at Acacemy.additionTest.AddZeroAndOne(additionTest.java:72)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddZeroAndOne -->
  <testcase name="AddZeroAndZero" time="5.263" classname="Acacemy.additionTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1.0E-10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1.0E-10]
at Acacemy.additionTest.AddZeroAndZero(additionTest.java:60)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- AddZeroAndZero -->
</testsuite> <!-- Addition -->
