<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-M4N4JHAP" ignored="0" name="Multiplication" tests="9" failures="9" timestamp="2021-03-14T15:52:08 GMT" time="61.705" errors="0">
  <testcase name="MultiplyAscendRangeAndDescendRange" time="7.088" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [38102050.0] but found [8.37389205E9]">
      <![CDATA[java.lang.AssertionError: expected [38102050.0] but found [8.37389205E9]
at Acacemy.multiplicationTests.MultiplyAscendRangeAndDescendRange(multiplicationTests.java:28)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyAscendRangeAndDescendRange -->
  <testcase name="MultiplyDecimalTwoPointTwoMinusOne" time="5.807" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [11.25] but found [11.2500000001]">
      <![CDATA[java.lang.AssertionError: expected [11.25] but found [11.2500000001]
at Acacemy.multiplicationTests.MultiplyDecimalTwoPointTwoMinusOne(multiplicationTests.java:87)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyDecimalTwoPointTwoMinusOne -->
  <testcase name="MultiplyMorethanTwoBigNumbers" time="5.964" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [6.789199772124E12] but found [6.7892332847724E13]">
      <![CDATA[java.lang.AssertionError: expected [6.789199772124E12] but found [6.7892332847724E13]
at Acacemy.multiplicationTests.MultiplyMorethanTwoBigNumbers(multiplicationTests.java:47)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyMorethanTwoBigNumbers -->
  <testcase name="MultiplyMorethanTwoNumbers" time="5.338" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [216.0] but found [2376.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [216.0] but found [2376.0000000001]
at Acacemy.multiplicationTests.MultiplyMorethanTwoNumbers(multiplicationTests.java:41)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyMorethanTwoNumbers -->
  <testcase name="MultiplyNegativeandPostiveNumbers" time="5.329" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [-35.0] but found [35.0000000001]">
      <![CDATA[java.lang.AssertionError: expected [-35.0] but found [35.0000000001]
at Acacemy.multiplicationTests.MultiplyNegativeandPostiveNumbers(multiplicationTests.java:81)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyNegativeandPostiveNumbers -->
  <testcase name="MultiplyOneAndZero" time="5.213" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1.0E-10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1.0E-10]
at Acacemy.multiplicationTests.MultiplyOneAndZero(multiplicationTests.java:75)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyOneAndZero -->
  <testcase name="MultiplyZeroAndOne" time="5.337" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1.0E-10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1.0E-10]
at Acacemy.multiplicationTests.MultiplyZeroAndOne(multiplicationTests.java:65)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyZeroAndOne -->
  <testcase name="MultiplyZeroAndZero" time="5.238" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1.0E-10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1.0E-10]
at Acacemy.multiplicationTests.MultiplyZeroAndZero(multiplicationTests.java:54)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplyZeroAndZero -->
  <testcase name="MultiplytwoNumbersBig" time="5.655" classname="Acacemy.multiplicationTests">
    <failure type="java.lang.AssertionError" message="expected [2.764000751148E12] but found [2.7463800107551217E18]">
      <![CDATA[java.lang.AssertionError: expected [2.764000751148E12] but found [2.7463800107551217E18]
at Acacemy.multiplicationTests.MultiplytwoNumbersBig(multiplicationTests.java:34)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- MultiplytwoNumbersBig -->
</testsuite> <!-- Multiplication -->
